### ISSUE TITLE
cell array error for levee breach

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1571] opened 2024-10-09 18:52 UTC
[Rio Grande Short.zip](https://github.com/user-attachments/files/17317351/Rio.Grande.Short.zip)

This is an imported project.  I wanted to set up a levee breach but I got an error about the cell array. 
So I deleted the old levee and rebuilt it using a short section.
Can you click the breach button and see if you get the error?

**Comment by rpachaly** [comment] 2024-10-09 19:01
What button exactly was triggering the error?

**Comment by FLO-2DKaren** [comment] 2024-10-09 21:12
Levee Breach button.

**Comment by rpachaly** [comment] 2024-10-10 11:07
It worked fine on my side.

**Comment by FLO-2DKaren** [comment] 2024-10-10 13:00
This button works?
It still isn't working for me.
![image](https://github.com/user-attachments/assets/31698d7b-c796-4ce6-a81f-1e5a5c8430bb)

**Comment by FLO-2DKaren** [comment] 2024-10-10 13:00
2024-10-10T08:59:43     WARNING    Traceback (most recent call last):
              File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\levee_and_breach_editor_widget.py", line 139, in show_levees
              dlg_individual_levees = IndividualLeveesDialog(self.iface, self.lyrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\dlg_breach.py", line 763, in __init__
              if cellIDNumpyArray is None:
              ^^^^^^^^^^^^^^^^
             NameError: name 'cellIDNumpyArray' is not defined

**Comment by rpachaly** [comment] 2024-10-10 13:08
Hi Karen, 

Yes, it is working fine here. Can you make a short video so I can see what is happening?

**Comment by FLO-2DKaren** [comment] 2024-10-10 13:11
https://github.com/user-attachments/assets/3a2466b0-2c28-4ed8-8a4a-90a32e66439b

**Comment by rpachaly** [comment] 2024-10-10 13:17
The project you sent to me is just a portion of the levee. Can you send this one that you're using? I don't see the error here.,

**Comment by FLO-2DKaren** [comment] 2024-10-10 13:19
Yes. I rebuild a short section to test it but it still wasn't working on my computer.
I'm going to restart my computer.
[Rio Grande Short orig.zip](https://github.com/user-attachments/files/17328781/Rio.Grande.Short.orig.zip)

**Comment by rpachaly** [comment] 2024-10-10 13:23
I got the error here! I was using an old plugin. Let me fix it.

**Comment by FLO-2DKaren** [comment] 2024-10-10 13:24
Yay!!!

**Comment by rpachaly** [comment] 2024-10-10 13:25
I was using an old qgis profile thinking that my plugin was updated. My bad

**Comment by rpachaly** [comment] 2024-10-10 13:36
This was caused by a removed import. It is a little weird, because it was a global variable.  Done and fixed on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1572

**Closed** 2024-10-17 15:51 UTC
Labels: bug, ready for testing
