### ISSUE TITLE
Display of Geopackage Spatial Reference After Creation

### ISSUE THREAD

**Issue by vaughanster** [FLO-2DSoftware/qgis-flo-2d-plugin#1380] opened 2024-06-19 22:03 UTC
Within the QGIS plug-in, when making a new geopackage once specifies the coordinate system like so:
![create_dialog_image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/17767336/ff3ca27f-27d2-498e-b0ac-06aab9a34fa0)

However, when using the same interface to view the information, the incorrect spatial reference is shown as so:
![view_dialog_image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/17767336/260342a2-54fa-4d14-a140-7ead2f1d79b6)

A check of the SQLite database shows the correct coordinate system is defined, just the display of it is incorrect in the QGIS interface.

**Comment by FLO-2DKaren** [comment] 2024-06-20 11:39
@vaughanster @rpachaly 

I think the issue is filling the label.  The code that fills the label is using proj or maybe wkt.  Instead of returning the correct coordinate system, it's returning the first one in line that almost matches.  There may be another reference we can use to sort this out.

**Comment by FLO-2DKaren** [comment] 2024-06-20 16:46
@vaughanster 

I think Robson resolved this with the Gila Plugin.  We'll probably just leave it as in on Plugin 115 and I'll look into Gila to make sure any CRS reference I can find is correct.

**Comment by FLO-2DKaren** [comment] 2024-06-20 16:53
I confirm that when you click the Settings button, you still get the correct coordinate system in the latest plugin version 

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/be2ec380-9d83-42e6-b1b4-f42d3eccfb42)

**Comment by FLO-2DKaren** [comment] 2024-06-26 14:53
I'm going to close this since it's only happening in the old version of the plugin.

**Closed by FLO-2DKaren** 2024-06-26 14:53 UTC
